name: hotfix-build

on:
  workflow_dispatch:
    inputs:
      hotfixTag:
        description: 'Hotfix Tag'
        required: true
        type: string
        choice:
          type: choice
          description: Make a choice
          options:
          - foo
          - bar
          - baz
    branches:
      - 'vinnie/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  tag:
    name: Set Vinnie version to tag name
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.hotfixTag }}

