name: main_registry 

on:
  push:
    branches:
      - 'logic_test'

jobs:
  node:
    strategy:
      matrix:
        env: [dev, stage, prod]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Set pipeline vars
        run: |
          echo "ECR_REGISTRY=753564379118.dkr.ecr.us-east-1.amazonaws.com" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=tilt_node_${{ matrix.env }}" >> $GITHUB_ENV
          echo "EKS_CLUSTER=tilt-${{ matrix.env }}" >> $GITHUB_ENV
          echo "NAMESPACE_NAME=${{ matrix.env }}" >> $GITHUB_ENV
          echo "ECR_SHA_TAG=${{ github.sha }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_API_PROTOCOL=https" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_JS_API_URL=ourtilt.${{ matrix.env }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_DJANGO_API_URL=api.ourtilt.${{ matrix.env }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_ADMIN_SUBDOMAIN=admin" >> $GITHUB_ENV
          if [[ "$matrix_env" == "dev" ]]
          then
            echo "found dev"
          elif [[ "$matrix_env" == "stage" ]]
          then
            echo "found stage" 
          elif [[ "$matrix_env" == "prod" ]]
          then 
            echo "found prod"
          else
            echo "no environment found"
          fi

      - name: Check runtime vars
        run: |
          echo "Registry = $ECR_REGISTRY"
          echo "Image repo = $ECR_REPOSITORY"
          echo "SHA = $ECR_SHA_TAG"
          echo "Version = $EKS_CLUSTER"
          echo "Environment = $NAMESPACE_NAME"
          echo "SHA = $ECR_SHA_TAG"
          echo "NEXT_PUBLIC_API_PROTOCOL = $NEXT_PUBLIC_API_PROTOCOL"
          echo "NEXT_PUBLIC_JS_API_URL = $NEXT_PUBLIC_JS_API_URL"
          echo "NEXT_PUBLIC_DJANGO_API_URL = $NEXT_PUBLIC_DJANGO_API_URL"
          echo "NEXT_PUBLIC_ADMIN_SUBDOMAIN = $NEXT_PUBLIC_ADMIN_SUBDOMAIN"