name: SF Hubstaff

on:
  workflow_dispatch:

env:
  ORG_ID: ${{ secrets.HS_ORG_ID }}
  ORG_NAME: '${{ secrets.HS_ORG_NAME }}'
  PROJECT_NAME: ${{ secrets.HS_PROJECT_NAME }}
  CLIENT_ID: ${{ secrets.HS_CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.HS_CLIENT_SECRET }}
  PAT: ${{ secrets.HS_PAT }}
  REFRESH_TOKEN: ${{ secrets.HS_REFRESH_TOKEN }}
  USERNAME: ${{ secrets.HS_USERNAME }}
  REDIRECT_URI: ${{ secrets.HS_REDIRECT_URI }}
  SCOPE:  'openid hubstaff:read'
  TOKEN_URL: 'https://account.hubstaff.com/access_tokens'
  BASE_URL: 'https://api.hubstaff.com/v2'
  USERS_FILE:  'hubstaff_users.csv'
  DATA_FOLDER: 'data/'

jobs:
  test-api-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          # For Ubuntu-based runners
          sudo apt-get update -y
          sudo apt-get install -y jq
        shell: bash
