name: SF Hubstaff

on:
  workflow_dispatch:

env:
  ORG_ID: ${{ secrets.ORG_ID }}
  ORG_NAME: '${{ secrets.ORG_NAME }}'
  PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  PAT: ${{ secrets.PAT }}
  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
  USERNAME: ${{ secrets.USERNAME }}
  REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
  SCOPE:  'openid hubstaff:read'
  TOKEN_URL: ${{ secrets.TOKEN_URL }}
  BASE_URL: ${{ secrets.BASE_URL }}
  USERS_FILE:  ${{ secrets.USERS_FILE }}
  DATA_FOLDER: ${{ secrets.DATA_FOLDER }}

jobs:
  test-api-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        id: python-setup
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3 python3-pip curl jq
          sudo ln -sf /usr/bin/python3 /usr/bin/python
          python --version
          pip --version
          pip install --upgrade pip
          pip install requests
          pip install python-dotenv

      - name: Run Main Script
        run: python main.py 2025-07-08
