name: Test API

on:
  workflow_dispatch:

jobs:
  test-api-token:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Test API Token
        run: |
          # Replace 'YOUR_API_ENDPOINT' with the actual API endpoint you want to test.
          API_ENDPOINT="http://api.zippopotam.us/us/80013"

          # Replace 'YOUR_API_TOKEN' with the actual API token you want to test.
          # API_TOKEN="YOUR_API_TOKEN"

          # Make an HTTP request to the API using curl.
          # RESPONSE=$(curl -s -H "Authorization: Bearer $API_TOKEN" "$API_ENDPOINT")

          # Check the HTTP response code. 200 means success.
          # if [[ "$(echo "$RESPONSE" | jq -r '.status')" == "200" ]]; then
          #   echo "API Token is valid."
          # else
          #   echo "API Token is invalid or the API request failed."
          #   exit 1
          # fi

          curl --location 'http://api.zippopotam.us/us/98121'

