name: Test API

on:
  workflow_dispatch:

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  OPENAI_ORG: ${{ secrets.OPENAI_ORG }}

jobs:
  test-api-token:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install jq
        run: |
          # For Ubuntu-based runners
          sudo apt-get update -y
          sudo apt-get install -y jq
        shell: bash

      - name: Test Public API endpoint
        run: |
          API_ENDPOINT="http://api.zippopotam.us/us/80013"
          curl --location $API_ENDPOINT

      - name: Test OpenAI API with Token
        run: |
          API_ENDPOINT="https://api.openai.com/v1/models"
          RESPONSE=$(curl "$API_ENDPOINT" -H "Authorization: Bearer $OPENAI_API_KEY" -H "OpenAI-Organization: $OPENAI_ORG")
          echo $RESPONSE | jq -r '.data[] | {id, model_name}'
